//
//  File.swift
//  LT Reviews
//
//  Created by Charlie Reeder on 5/14/22.
//

import Foundation

/*
 "Firstname Lastname" : [
         "Salary" : ["64_450"],
         "Hard Grader" : ["3"],
         "Nice/Fun" : ["4"],
         "Teaching Ability" : ["5"],
         "Rating" : ["4.3"],
         "Reviews" : ["I hate this  so much"],
         "Upvotes" : ["3", "44", "5", "3", "268", "45", "0", "8"]
     ],
 */

enum StaticTeacherProperty {
    case department, email, salary
}
//MARK: IMPORTANT THAT SALARY IS WITHOUT BENEFITS AND PENSION, NOTE
let StaticTeacherInfo: [String : [StaticTeacherProperty : String]] = [

    "Rachel Agosta"            : [.department : "Math",              .email : "ragosta@cps.edu",          .salary : "0"],
    "Ricardo Alejo"            : [.department : "Special Education", .email : "raalejo@cps.edu",          .salary : "0"],
    "Darius Alexander"         : [.department : "Security",          .email : "dalexander68@cps.edu",     .salary : "0"],
    "Julie Allen"              : [.department : "Drama",             .email : "jcallen10@cps.edu",        .salary : "0"],
    "Nadia Almutairi"          : [.department : "ESP",               .email : "nalmutairi@cps.edu",       .salary : "34662"],
    "Smith Ana"                : [.department : "Lunchroom",         .email : "asmith96@cps.edu",         .salary : "0"],
    "Dana Anderson"            : [.department : "World Language",    .email : "dhuang10@cps.edu",         .salary : "42799"],
    "Amanda Andros"            : [.department : "Counseling",        .email : "akandros@cps@cps.edu",     .salary : "0"],
    "Temuulen Ankhbayar"       : [.department : "ESP",               .email : "tankhbayar1@cps.edu",      .salary : "0"],
    "Fatima Anton"             : [.department : "Math",              .email : "fanton@cps@cps.edu",       .salary : "83652"],
    "Nissa Applequist"         : [.department : "Social Science",    .email : "NAApplequist@cps@cps.edu", .salary : "0"],
    "Damir Ara"                : [.department : "Administration",    .email : "DMAra@cps@cps.edu",        .salary : "0"],
    "Lizette Arroyo"           : [.department : "Counseling",        .email : "larroyo33@cps.edu",        .salary : "0"],
    "Nicholas Arvanitakis"     : [.department : "Special Education", .email : "narvanitakis@cps.edu",     .salary : "0"],
    "Julie Atkocaitis"         : [.department : "Counseling",        .email : "jaatkocaitis1@cps.edu",    .salary : "0"],
    "Rebecca Atwood"           : [.department : "Math",              .email : "ratwood@cps.edu",          .salary : "0"],
    "Meredith Bantz"           : [.department : "Counseling",        .email : "mabantz@cps.edu",          .salary : "0"],
    "Joy Barrows"              : [.department : "Math",              .email : "JDBarrows@cps.edu",        .salary : "0"],
    "Robert Bartelt"           : [.department : "Science",           .email : "rwbartelt@cps.edu",        .salary : "0"],
    "Patrick Bartman"          : [.department : "Technology",        .email : "pebartman@cps.edu",        .salary : "0"],
    "Jeffrey Batt"             : [.department : "Science",           .email : "jabatt@cps.edu",           .salary : "0"],
    "Barbara Becker"           : [.department : "Math",              .email : "bbecker@cps.edu",          .salary : "0"],
    "Robert Berg"              : [.department : "Computer Science",  .email : "rberg@cps.edu",            .salary : "0"],
    "Stephanie Trejo"          : [.department : "Special Education", .email : "sberryhill1@cps.edu",      .salary : "0"],
    "Amanda Bessette"          : [.department : "English",           .email : "aedamlos@cps.edu",         .salary : "0"],
    "Bayinnah Bey"             : [.department : "English",           .email : "BBey@cps.edu",             .salary : "0"],
    "Rosa Blanco"              : [.department : "Special Education", .email : "rmblanco1@cps.edu",        .salary : "0"],
    "Matthew Bobek"            : [.department : "Phys Ed",           .email : "mbobek@cps.edu",           .salary : "0"],
    "Linley Bosse"             : [.department : "Math",              .email : "lbosse1@cps.edu",          .salary : "0"],
    "Dinieka Boston"           : [.department : "Special Education", .email : "DLBoston@cps.edu",         .salary : "0"],
    "Brent Bradish"            : [.department : "Social Science",    .email : "BWBradish@cps.edu",        .salary : "0"],
    "Maureen Bradish"          : [.department : "Special Education", .email : "masmith9@cps.edu",         .salary : "0"],
    "Sean Bratton"             : [.department : "Science",           .email : "sbratton1@cps.edu",        .salary : "0"],
    "Angela Burbano"           : [.department : "World Language",    .email : "AJBurbano@cps.edu",        .salary : "0"],
    "Margaret Burgoss"         : [.department : "ESP",               .email : "mburgos9@cps.edu",         .salary : "0"],
    "Jessica Campos"           : [.department : "Attendance",        .email : "jcampos3@cps.edu",         .salary : "0"],
    "David Campos"             : [.department : "Social Science",    .email : "dcampos24@cps.edu",        .salary : "0"],
    "Julie Caracci"            : [.department : "Social Science",    .email : "jlcaracci@cps.edu",        .salary : "0"],
    "Jeffrey Carity"           : [.department : "Social Science",    .email : "jmcarity@cps.edu",         .salary : "0"],
    "Randall Carpenter"        : [.department : "Counseling",        .email : "rcarpenter3@cps.edu",      .salary : "0"],
    "Amy Carqueville"          : [.department : "Counseling",        .email : "akcarquevill@cps.edu",     .salary : "0"],
    "Mark Carrera"             : [.department : "Music",             .email : "MCarrera@cps.edu",         .salary: "0"],
    "Paul Carrera"             : [.department : "Music",             .email : "PACarrera@cps.edu",        .salary: "0"],
    "Taryn Carter"             : [.department : "Library",           .email : "tcarter64@cps.edu",        .salary: "0"],
    "Pei Yeu Chang"            : [.department : "World Language",    .email : "pchang2@cps.edu",          .salary: "0"],
    "Lisa Chappell"            : [.department : "English",           .email : "LMChappell@cps.edu",       .salary: "0"],
    "Brandon Chavez"           : [.department : "Special Education", .email : "Bchavez43@cps.edu", .salary: "0"],
    "Elizabeth Chisholm"       : [.department : "Art",               .email : "echisholm@cps.edu", .salary: "0"],
    "Christina Clemons"        : [.department : "Special Education", .email : "clclemons@cps.edu", .salary: "0"],
    "Joshua Cockrell"          : [.department : "Social Science",    .email : "JPCockrell@cps.edu", .salary: "0"],
    "Thomas Cogdall"           : [.department : "JROTC",             .email : "tcogdall@cps.edu", .salary: "0"],
    "April Coleman"            : [.department : "English",           .email : "APColeman@cps.edu", .salary: "0"],
    "David Colon"              : [.department : "Security",          .email : "DColon2@cps.edu", .salary: "0"],
    "Jessica Colvin"           : [.department : "Phys Ed",           .email : "jmcolvin@cps.edu", .salary: "0"],
    "Miles Comiskey"           : [.department : "Music",             .email : "mcomiskey@cps.edu", .salary: "0"],
    "Rosanna Console"          : [.department : "Counseling",        .email : "RConsole@cps.edu", .salary: "0"],
    "Nikki Constantine"        : [.department : "Counseling",        .email : "nconstantin@cps.edu", .salary: "0"],
    "Jessica Coonley"          : [.department : "Science",           .email : "jgcox@cps.edu", .salary: "0"],
    "Jack Cox"                 : [.department : "Support Staff",     .email : ".edu", .salary: "0"],
    "Elizabeth Cramarosso"     : [.department : "English",           .email : "eacramarosso@cps.edu", .salary: "0"],
    "Marjorrie Custodio"       : [.department : "Art",               .email : "mccustodio@cps.edu", .salary: "0"],
    "Jessica Cwiak"            : [.department : "English",           .email : "jacwiak@cps.edu", .salary: "0"],
    "Diamond Dadej"            : [.department : "Social Science",    .email : "dadadej@cps.edu", .salary: "0"],
    "Rebecca Daly"             : [.department : "Social Science",    .email : "radaly@cps.edu", .salary: "0"],
    "Mohamed Danja"            : [.department : "World Language",    .email : "mdanja@cps.edu", .salary: "0"],
    "Sara Darbyshire"          : [.department : "Science",           .email : "sdfranzen@cps.edu", .salary: "0"],
    "Patrick Davey"            : [.department : "Science",           .email : "padavey@cps.edu", .salary: "0"],
    "Ann Marie Davis"          : [.department : "Phys Ed",           .email : "AMLarocco@cps.edu", .salary: "0"],
    "Soren Davis"              : [.department : "Special Education",           .email: "smdavis10.edu", .salary: "0"],
    "Brooke Day"               : [.department : "Science",             .email: "bagaynor@cps.edu", .salary: "0"],
    "Gerald DeMar"             : [.department : "JROTC",                   .email: "GDDemar@cps.edu", .salary: "0"],
    "Katherine Delisle"        : [.department : "Math", .              email: "kjdelisle@cps.edu", .salary: "0"],
    "Amy Diamond"              : [.department : "Art", .                email: "amdiamond@cps.edu", .salary: "0"],
    "David Doll"               : [.department : "Social Science", .email: "ddoll@cps.edu", .salary: "0"],
    "Sandy Donahue"            : [.department : "Math", .email: "sdonahue3@cps.edu", .salary: "0"],
    "Eugenia Dongas"           : [.department : "Science", .email: "emaglaris@cps.edu", .salary: "0"],
    "Joshua Dresser"           : [.department : "Administration", .email: "jcdresser@cps.edu", .salary: "0"],
    "Sarah Hanly"              : [.department : "Administration", .email: "schanly@cps.edu", .salary: "0"],
    "Mollie Hart"              : [.department : "Administration", .email: "MAHart@cps.edu", .salary: "0"],
    "Gabrielaa Escobar"        : [.department : "Administration", .email: "gbescobar@cps.edu", .salary: "0"],
    "Alison Hildebrandt"       : [.department : "Administration", .email: "avkrakowski@cps.edu", .salary: "0"],
    "Tara Johnson"             : [.department : "Administration", .email: "tecarroll@cps.edu", .salary: "0"],
    "Norman Milsap"            : [.department : "Administration", .email: "NPMilsap@cps.edu", .salary: "0"],
    "Kerri Thompson"           : [.department : "Administration", .email: "kathompson@cps.edu", .salary: "0"],
    "Edwina Thompson"          : [.department : "Administration", .email: "ELGholston@cps.edu", .salary: "0"],
    "Sarah Wain"               : [.department : "Art", .email: "sawin@cps.edu", .salary: "0"],
    "Greg Steffens"            : [.department: "Art", .email: "gjsteffens@cps.edu", .salary: "0"],
    "Kristina Simanis-Laimins" : [.department: "Art", .email: "KRSimanis@cps.edu", .salary: "0"],
    "Benjamin Oshana"          : [.department: "Art", .email: "boshana@cps.edu", .salary: "0"],
    "Kelly Novak"              : [.department: "Art", .email: "knovak1@cps.edu", .salary: "0"],
    "Michael Morrison"         : [.department: "Art", .email: "mamorrison@cps.edu", .salary: "0"],
    "Liana Faletto"            : [.department: "Art", .email: "lafaletto@cps.edu", .salary: "0"],
    "Rick Ceh"                 : [.department: "Art", .email: "RTCeh@cps.edu", .salary: "0"],
    "April Navarrete"          : [.department: "Attendance", .email: "agnavarrete.edu", .salary: "0"],
    "Matthew Yan"              : [.department: "Computer Science", .email: "mjyan@cps.edu", .salary: "0"],
    "Amy Wozniak"              : [.department: "Computer Science", .email: "ajwozniak@cps.edu", .salary: "0"],
    "Daniel Stone"             : [.department: "Computer Science", .email: "dgstone@cps.edu", .salary: "0"],
    "Jeffrey Solin"            : [.department: "Computer Science", .email: "JBSolin@cps.edu", .salary: "0"],
    "Jennifer Roscoe"          : [.department: "Computer Science", .email: "jhinz@cps.edu", .salary: "0"],
    "Brenda Remess"            : [.department: "Computer Science", .email: "bremess@cps.edu", .salary: "0"],
    "Jaimin Patel"             : [.department: "Computer Science", .email: "jvpatel@cps.edu", .salary: "0"],
    "Daniel Law"               : [.department: "Computer Science", .email: "drlaw@cps.edu", .salary: "0"],
    "Tenzin Langchung"         : [.department: "Computer Science", .email: "tplangchung@cps.edu", .salary: "0"],
    "Leon Kim"                 : [.department: "Computer Science", .email: "lhkim@cps.edu", .salary: "0"],
    "Marta Johnson"            : [.department: "Computer Science", .email: "msjohnson@cps.edu", .salary: "0"],
    "Heather Saylor"           : [.department: "Counseling", .email: "hsayalor@cps.edu", .salary: "0"],
    "Hitomi Oum"               : [.department: "Counseling", .email: "houm@cps.edu", .salary: "0"],
    "Nakia Morgan"             : [.department: "Counseling", .email: "nablanton-mo@cps.edu", .salary: "79733"],
    "Aaron Hoof"               : [.department: "Counseling", .email: "@amhoofcps.edu", .salary: "0"],
    "Shannon Fuhrmann" : [.department: "Counseling", .email: "sfuhrmann@cps.edu", .salary: "0"],
    "Erin Driesbach" : [.department: "Counseling", .email: "eadriesbach@cps.edu", .salary: "0"],
    "Molly Meacham" : [.department: "Drama", .email: "mmeacham@cps.edu", .salary: "0"],
    "Kirsten Hanson" : [.department: "Drama", .email: "@kdhansoncps.edu", .salary: "0"],
    "Jill Woods" : [.department: "ESP", .email: "jmwoods@cps.edu", .salary: "0"],
    "Emilyna Villasenor" : [.department: "ESP", .email: "emvillasenor1@cps.edu", .salary: "0"],
    "Dannixa Velez" : [.department: "ESP", .email: "dlvelez1@cps.edu", .salary: "0"],
    "Veronika Schroeder" : [.department: "ESP", .email: "vschroeder@cps.edu", .salary: "0"],
    "Miriam Santana" : [.department: "ESP", .email: "MSantana@cps.edu", .salary: "0"],
    "Rodrigo Salgado" : [.department: "ESP", .email: "rsalgado28@cps.edu", .salary: "0"],
    "Michael Penick" : [.department: "ESP", .email: "mpenick@cps.edu", .salary: "0"],
    "Amber McDonald" : [.department: "ESP", .email: "acmcdonald@cps.edu", .salary: "0"],
    "Nyla Mallett" : [.department: "ESP", .email: "nmallett1@cps.edu", .salary: "0"],
    "Rene Luis" : [.department: "ESP", .email: "rluis@cps.edu", .salary: "0"],
    "Rose Givhan" : [.department: "ESP", .email: "rmgivhan@cps.edu", .salary: "0"],
    "Elise Zerega" : [.department: "English", .email: "ezerega@cps.edu", .salary: "0"],
    "Shakura Weathers" : [.department: "English", .email: "srweathers@cps.edu", .salary: "0"],
    "Michelle Vale" : [.department: "English", .email: "MVale@cps.edu", .salary: "0"],
    "Corrina Ulmer" : [.department: "English", .email: "culmer@cps.edu", .salary: "0"],
    "Lizzette Trujillo" : [.department: "English", .email: "lvtrujillo@cps.edu", .salary: "0"],
    "Brian Telles" : [.department: "English", .email: "BCTelles@cps.edu", .salary: "0"],
    "David Strom" : [.department: "English", .email: "DAStrom@cps.edu", .salary: "0"],
    "Kristen Starr" : [.department: "English", .email: "KJStarr@cps.edu", .salary: "0"],
    "Joshua Smith" : [.department: "English", .email: "Jsmith461@cps.edu", .salary: "0"],
    "Dipa Shah" : [.department: "English", .email: "dshah5@cps.edu", .salary: "0"],
    "Sahar Shafqat" : [.department: "English", .email: "sshafqat@cps.edu", .salary: "0"],
    "Elizabeth Serilla" : [.department: "English", .email: "ewserilla@cps.edu", .salary: "0"],
    "Alexandra Sears" : [.department: "English", .email: "asears2@cps.edu", .salary: "0"],
    "Nathan Nordlund" : [.department: "English", .email: "ntnordlund@cps.edu", .salary: "0"],
    "Michelle Mottram-Dummeldinger" : [.department: "English", .email: "mcmottram-du@cps.edu", .salary: "0"],
    "Haleemeh Mikbel" : [.department: "English", .email: "HMikbel@cps.edu", .salary: "0"],
    "Meghan McDonough" : [.department: "English", .email: "mmmcdonough1@cps.edu", .salary: "0"],
    "Theresa Mathew" : [.department: "English", .email: "ttmathew@cps.edu", .salary: "0"],
    "Valerie Mason" : [.department: "English", .email: "vhouse@cps.edu", .salary: "0"],
    "Curt Maslanka" : [.department: "English", .email: "rcmaslanka@cps.edu", .salary: "0"],
    "Nicholas Logalbo" : [.department: "English", .email: "NFLogalbo@cps.edu", .salary: "0"],
    "Nicholas Locke" : [.department: "English", .email: "nlocke@cps.edu", .salary: "0"],
    "Katharine Laroche" : [.department: "English", .email: "kelaroche1@cps.edu", .salary: "0"],
    "Hans Kim" : [.department: "English", .email: "hkim11@cps.edu", .salary: "0"],
    "Alysia Hesse" : [.department: "Counseling", .email: "ahesse@cps.edu", .salary: "0"],
    "Dane Haiken" : [.department: "English", .email: "dhaiken@cps.edu", .salary: "0"],
    "Maria Flores" : [.department: "English", .email: "DFlores@cps.edu", .salary: "0"],
    "Andrew Fine" : [.department: "English", .email: "asfine@cps.edu", .salary: "0"],
    "Courtney Feuer" : [.department: "English", .email: "CRFeuer@cps.edu", .salary: "0"],
    "Katherine Ewers" : [.department: "English", .email: "kfewers@cps.edu", .salary: "0"],
    "Ricardo Torres" : [.department: "JROTC", .email: "RTorres1@cps.edu", .salary: "0"],
    "Ramona Woodson" : [.department: "Lunchroom", .email: "RMWoodson@cps.edu", .salary: "0"],
    "Irma Suarez" : [.department: "Lunchroom", .email: "ijsuarez@cps.edu", .salary: "0"],
    "Aruna Patel" : [.department: "Lunchroom", .email: "apatel14@cps.edu", .salary: "0"],
    "Maria Meza" : [.department: "Lunchroom", .email: "mrmeza1@cps.edu", .salary: "0"],
    "Donald Jackson" : [.department: "Lunchroom", .email: "DJackson13@cps.edu", .salary: "0"],
    "Juana Hernandez" : [.department: "Lunchroom", .email: "jhernandez456@cps.edu", .salary: "0"],
    "Diana Esquivel" : [.department: "Math", .email: "dlblack@cps.edu", .salary: "0"],
    "Kirstin Glawe" : [.department: "Math", .email: "kglawe@cps.edu", .salary: "0"],
    "Eric Golden" : [.department: "Math", .email: "EAGolden@cps.edu", .salary: "0"],
    "Mark Hamel" : [.department: "Math", .email: "mhamel@cps.edu", .salary: "0"],
    "Mallorie Hsieh" : [.department: "Math", .email: "mhsieh@cps.edu", .salary: "0"],
    "Lauren Jencius" : [.department: "Math", .email: "LMJencius@cps.edu", .salary: "0"],
    "Thomas Kane" : [.department: "Math", .email: "tkane@cps.edu", .salary: "0"],
    "Cynthia Kim" : [.department: "Math", .email: "cckim@cps.edu", .salary: "0"],
    "Kathy LaMark" : [.department: "Math", .email: "kgarbis@cps.edu", .salary: "0"],
    "Shoshana Levy" : [.department: "Math", .email: "srlevy2@cps.edu", .salary: "0"],
    "Katherin Marino" : [.department: "Math", .email: "KMarino@cps.edu", .salary: "0"],
    "Nicholas Markese" : [.department: "Math", .email: "njmarkese@cps.edu", .salary: "0"],
    "Daina Matusaitis" : [.department: "Math", .email: "dmatusaitis@cps.edu", .salary: "0"],
    "Andrew Minor" : [.department: "Math", .email: "ASMinor@cps.edu", .salary: "0"],
    "Matthew Neesan" : [.department: "Math", .email: "mmneesan@cps.edu", .salary: "0"],
    "Almasa Pecanin" : [.department: "Math", .email: "apecanin2@cps.edu", .salary: "0"],
    "Kyle Perfect" : [.department: "Math", .email: "ktperfect@cps.edu", .salary: "0"],
    "Jodie Pflaum" : [.department: "Math", .email: "jmpflaum@cps.edu", .salary: "0"],
    "Emily Salzman" : [.department: "Math", .email: "esalzman@cps.edu", .salary: "0"],
    "Hannah Schuchhardt" : [.department: "Math", .email: "hykwon@cps.edu", .salary: "0"],
    "Jeffrey Sevener" : [.department: "Math", .email: "jmsevener@cps.edu", .salary: "0"],
    "Abigail Smith" : [.department: "Math", .email: "asmith420@cps.edu", .salary: "0"],
    "Daniel Spedale" : [.department: "Math", .email: "djspedale@cps.edu", .salary: "0"],
    "Monica Stevenson" : [.department: "Math", .email: "mastevenson1@cps.edu", .salary: "0"],
    "David Willmore" : [.department: "Math", .email: "dpwillmore@cps.edu", .salary: "0"],
    "Samuel Veren" : [.department: "Music", .email: "sveren@cps.edu", .salary: "0"],
    "Joe Sweet" : [.department: "Music", .email: "jsweet2@cps.edu", .salary: "0"],
    "Ben Saltz" : [.department: "Music", .email: "basaltz@cps.edu", .salary: "0"],
    "Javier Payano" : [.department: "Music", .email: "jrpayano@cps.edu", .salary: "0"],
    "Devon Morales" : [.department: "Music", .email: "dreedy1@cps.edu", .salary: "0"],
    "A. Reed Flygt" : [.department: "Math", .email: "aflygt@cps.edu", .salary: "0"],
    "Michael Guzzarde" : [.department: "Phys Ed", .email: "mjguzzarde@cps.edu", .salary: "0"],
    "Susan Onken" : [.department: "Phys Ed", .email: "SOnken@cps.edu", .salary: "0"],
    "Matthew O'Hagan" : [.department: "Phys Ed", .email: "mohagan1@cps.edu", .salary: "0"],
    "Gregg Mitchell" : [.department: "Phys Ed", .email: "GRMitchell@cps.edu", .salary: "0"],
    "Jane Milsap" : [.department: "Phys Ed", .email: "JECallahan@cps.edu", .salary: "0"],
    "Francisco Marchan" : [.department: "Phys Ed", .email: "FJMarchan@cps.edu", .salary: "0"],
    "Brian Hofman" : [.department: "Phys Ed", .email: "BSHofman@cps.edu", .salary: "0"],
    "Amy Heveran" : [.department: "Phys Ed", .email: "amheveran@cps.edu", .salary: "0"],
    "Chantelle Fregoso" : [.department: "Phys Ed", .email: "crpadilla@cps.edu", .salary: "0"],
    "James Floyd" : [.department: "Phys Ed", .email: "jdfloyd1@cps.edu", .salary: "0"],
    "Kevin Ziolo" : [.department: "Science", .email: "kziolo@cps.edu", .salary: "0"],
    "Lucy Young" : [.department: "Science", .email: "layoung1@cps.edu", .salary: "0"],
    "Glenn Wilson" : [.department: "Science", .email: "GEWilson1@cps.edu", .salary: "0"],
    "Arthur Wawrzyczek" : [.department: "Science", .email: "awawrzyczek@cps.edu", .salary: "0"],
    "Jennifer Vetvick" : [.department: "Science", .email: "JVetvick@cps.edu", .salary: "0"],
    "Scott Vessalo" : [.department: "Science", .email: "smvessalo@cps.edu", .salary: "0"],
    "Jennifer Snyder" : [.department: "Science", .email: "JLSnyder1@cps.edu", .salary: "0"],
    "Julie Smallfield" : [.department: "Science", .email: "jsmallfield@cps.edu", .salary: "0"],
    "Leah Roskin" : [.department: "Science", .email: "leroskin@cps.edu", .salary: "0"],
    "Javier Reyes" : [.department: "Science", .email: "jreyes249@cps.edu", .salary: "0"],
    "Brian Reid" : [.department: "Science", .email: "BJReid1@cps.edu", .salary: "0"],
    "Peter Pissios" : [.department: "Science", .email: "pwpissios@cps.edu", .salary: "0"],
    "Andrew Pindelski" : [.department: "Science", .email: "adpindelski@cps.edu", .salary: "0"],
    "Josh Park" : [.department: "Science", .email: "jpark19@cps.edu", .salary: "0"],
    "Katrin Machaj" : [.department: "Science", .email: "KMachaj@cps.edu", .salary: "0"],
    "Michelle Loh" : [.department: "Science", .email: "mmendez50@cps.edu", .salary: "0"],
    "David Liebenson" : [.department: "Science", .email: "dcliebenson@cps.edu", .salary: "0"],
    "Elizabeth Lee" : [.department: "Science", .email: "ellee1@cps.edu", .salary: "0"],
    "Nicholas Lang" : [.department: "Science", .email: "nlang@cps.edu", .salary: "0"],
    "Jeffrey Kallen" : [.department: "Science", .email: "jmkallen1@cps.edu", .salary: "0"],
    "Karlene Joseph" : [.department: "Science", .email: "KBJoseph@cps.edu", .salary: "0"],
    "John Hollowed" : [.department: "Science", .email: "JRHollowed@cps.edu", .salary: "0"],
    "Leah Herlocker" : [.department: "Science", .email: "lherlocker@cps.edu", .salary: "0"],
    "Kelly Heath" : [.department: "Science", .email: "KAHeath@cps.edu", .salary: "0"],
    "Roy Hays" : [.department: "Science", .email: "rchays@cps.edu", .salary: "0"],
    "Carol Guy" : [.department: "Science", .email: "CGuy@cps.edu", .salary: "0"],
    "Katharine Gomez" : [.department: "Math", .email: "KTGomez1@cps.edu", .salary: "0"],
    "Debra Dossing" : [.department: "Math", .email: "dadossing@cps.edu", .salary: "0"],
    "Kenneth Wright" : [.department: "Security", .email: "KOWright@cps.edu", .salary: "0"],
    "Michael Smith" : [.department: "Security", .email: "msmith24@cps.edu", .salary: "0"],
    "Gerardo Servin" : [.department: "Security", .email: "gservin2@cps.edu", .salary: "0"],
    "Lourdes Rodriguez" : [.department: "Security", .email: "LRodriguez11@cps.edu", .salary: "0"],
    "Kabir Omerovic" : [.department: "Security", .email: "komerovic@cps.edu", .salary: "0"],
    "Miguel Olivo" : [.department: "Security", .email: "MAOlivo@cps.edu", .salary: "0"],
    "Catherine Jackson" : [.department: "Security", .email: "CMJackson@cps.edu", .salary: "0"],
    "Rose Hernandez" : [.department: "Security", .email: "RMHernandez2@cps.edu", .salary: "0"],
    "Jerry Hall" : [.department: "Security", .email: "JBHall@cps.edu", .salary: "0"],
    "Kyle Frapolly" : [.department: "Security", .email: "kmfrapolly@cps.edu", .salary: "0"],
    "Irving Zamudio" : [.department: "Social Science", .email: "izamudio5@cps.edu", .salary: "0"],
    "Peter Vlahos" : [.department: "Social Science", .email: "PAVlahos@cps.edu", .salary: "0"],
    "Bryan Tyrpin" : [.department: "Social Science", .email: "btyrpin@cps.edu", .salary: "0"],
    "Tina-Marie Turner" : [.department: "Social Science", .email: "TTurner@cps.edu", .salary: "0"],
    "George Svarnias" : [.department: "Social Science", .email: "GLSvarnias@cps.edu", .salary: "0"],
    "Paul Stepek" : [.department: "Social Science", .email: "PEStepek@cps.edu", .salary: "0"],
    "Melissa Smith" : [.department: "Social Science", .email: "MKSmith@cps.edu", .salary: "0"],
    "Susan Sebestyen" : [.department: "Social Science", .email: "SVSebestyen@cps.edu", .salary: "0"],
    "Joseph Ruckauf" : [.department: "Social Science", .email: "JPRuckauf@cps.edu", .salary: "0"],
    "Steven Parsons" : [.department: "Social Science", .email: "stparsons@cps.edu", .salary: "0"],
    "Emily Paras" : [.department: "Social Science", .email: "eparas@cps.edu", .salary: "0"],
    "Mario Nunez" : [.department: "Social Science", .email: "manunez10@cps.edu", .salary: "0"],
    "Katherine Nester" : [.department: "Social Science", .email: "KLNester@cps.edu", .salary: "0"],
    "Michael McNaughton" : [.department: "Social Science", .email: "MJMcnaughton@cps.edu", .salary: "0"],
    "Erin McMahon" : [.department: "Social Science", .email: "eemcmahon1@cps.edu", .salary: "0"],
    "Laura McKnight" : [.department: "Social Science", .email: "lmcknight1@cps.edu", .salary: "0"],
    "Amanda Malstrom" : [.department: "Social Science", .email: "ALMalstrom@cps.edu", .salary: "0"],
    "Kenneth Lewis" : [.department: "Social Science", .email: "KWLewis1@cps.edu", .salary: "0"],
    "Timothy Hopps" : [.department: "Social Science", .email: "thopps1@cps.edu", .salary: "0"],
    "Robert Harkness" : [.department: "Social Science", .email: "rsharkness@cps.edu", .salary: "0"],
    "Gerardo Gonzalez" : [.department: "Social Science", .email: "ggonzalez138@cps.edu", .salary: "0"],
    "Marrin Gillespie" : [.department: "Social Science", .email: "mgillespie4@cps.edu", .salary: "0"],
    "Emily Freedman" : [.department: "Social Science", .email: "efreedman@cps.edu", .salary: "0"],
    "Thomas Fitzpatrick" : [.department: "Social Science", .email: "tfitzpatrick@cps.edu", .salary: "0"],
    "Timothy Escudier" : [.department: "Social Science", .email: "TMEscudier@cps.edu", .salary: "0"],
    "Kevin Kahler" : [.department: "Support Staff", .email: "kkahler@cps.edu", .salary: "0"],
    "Laura McLaughlin-Kantowicz" : [.department: "Support Staff", .email: "lmclaughlinkantowicz@cps.edu", .salary: "0"],
    "Noelle Natoli" : [.department: "Support Staff", .email: "nmnatoli@cps.edu", .salary: "0"],
    "Susan Sell" : [.department: "Support Staff", .email: "srsell@cps.edu", .salary: "0"],
    "Meagan Walsh" : [.department: "Support Staff", .email: "mwalsh15@cps.edu", .salary: "0"],
    "Stephanie Yanaga" : [.department: "Support Staff", .email: "smdumire@cps.edu", .salary: "0"],
    "Velibor Nikolic" : [.department: "Technology", .email: "vnikolic1@cps.edu", .salary: "0"],
    "Kaitlyn Krone" : [.department: "World Language", .email: "kakrone@cps.edu", .salary: "0"],
    "Juanita Mendoza" : [.department: "World Language", .email: "jmendoza147@cps.edu", .salary: "0"],
    "Grace Navarrete" : [.department: "World Language", .email: "gnavarrete2@cps.edu", .salary: "0"],
    "M. Patricia Paganelli" : [.department: "World Language", .email: "PPaganelli@cps.edu", .salary: "0"],
    "Lucy Perez" : [.department: "World Language", .email: "LPerez1@cps.edu", .salary: "0"],
    "Daniel Polley" : [.department: "World Language", .email: "DJPolley@cps.edu", .salary: "0"],
    "Celeste Ramovic" : [.department: "World Language", .email: "cramovic@cps.edu", .salary: "0"],
    "Andrew Ricks" : [.department: "World Language", .email: "AJRicks@cps.edu", .salary: "0"],
    "Sundy Satsu" : [.department: "World Language", .email: "sksatsu@cps.edu", .salary: "0"],
    "David Silverstein" : [.department: "World Language", .email: "DSSilverstein@cps.edu", .salary: "0"],
    "Edwardo Sosa" : [.department: "World Language", .email: "ESosa@cps.edu", .salary: "0"],
    "Lisa Tacke-Pucylowski" : [.department: "World Language", .email: "LKTacke@cps.edu", .salary: "0"],
    "Leticia Zuniga" : [.department: "World Language", .email: "LZuniga@cps.edu", .salary: "0"],
    "Jesus Jimenez" : [.department: "World Language", .email: "JJimenez3@cps.edu", .salary: "0"],
    "Henry Gomez" : [.department: "World Language", .email: "hgomez14@cps.edu", .salary: "0"],
    "Zeljka Girardi" : [.department: "World Language", .email: "zgirardi@cps.edu", .salary: "0"],
    "Misty Esguerra" : [.department: "World Language", .email: "mesguerra@cps.edu", .salary: "0"],
    "Freddy Enriquez" : [.department: "World Language", .email: "fenriquez@cps.edu", .salary: "0"],
    "Phillip Elkins" : [.department: "World Language", .email: "PElkins@cps.edu", .salary: "0"],
    "Migdalia Sepulveda" : [.department: "Special Education", .email: "MSepulveda@cps.edu", .salary: "0"],
    "Nida Sheikh" : [.department: "Special Education", .email: "nrsheikh@cps.edu", .salary: "0"],
    "Jessica Sherwin" : [.department: "Special Education", .email: "jsherwin@cps.edu", .salary: "0"],
    "Kiara Stanley" : [.department: "Special Education", .email: "krstanley1@cps.edu", .salary: "0"],
    "Jillian Strauch" : [.department: "Special Education", .email: "jstrauch@cps.edu", .salary: "0"],
    "Allison Vitale" : [.department: "Special Education", .email: "arvitale@cps.edu", .salary: "0"],
    "Amy Wallace" : [.department: "Special Education", .email: "aewallace3@cps.edu", .salary: "0"],
    "Tiffany Williams" : [.department: "Special Education", .email: "TSWilliams1@cps.edu", .salary: "0"],
    "David Yaffe" : [.department: "Special Education", .email: "DEYaffe@cps.edu", .salary: "0"],
    "Tamara Yamaji" : [.department: "Special Education", .email: "ttyamaji@cps.edu", .salary: "0"],
    "Sonya Marrero" : [.department: "Special Education", .email: "samarrero@cps.edu", .salary: "0"],
    "Anyuta Mihova" : [.department: "Special Education", .email: "admihova@cps.edu", .salary: "0"],
    "Anna Mullin" : [.department: "Special Education", .email: "amsieczkowsk@cps.edu", .salary: "0"],
    "Jonathan Negron" : [.department: "Special Education", .email: "jnegron20@cps.edu", .salary: "0"],
    "Joan Noonan" : [.department: "Special Education", .email: "jnoonan4@cps.edu", .salary: "0"],
    "Dan O'Donnell" : [.department: "Special Education", .email: "DCOdonnell@cps.edu", .salary: "0"],
    "Mirjana O'Hara" : [.department: "Special Education", .email: "MSOhara@cps.edu", .salary: "0"],
    "Brian Olamit" : [.department: "Special Education", .email: "bkolamit@cps.edu", .salary: "0"],
    "Maria Artemia Olea" : [.department: "Special Education", .email: "AMOlea@cps.edu", .salary: "0"],
    "Savana Ramos" : [.department: "Special Education", .email: "srramos4@cps.edu", .salary: "0"],
    "Angie Rankin" : [.department: "Special Education", .email: "garankin@cps.edu", .salary: "0"],
    "Clara Reyes" : [.department: "Special Education", .email: "creyes90@cps.edu", .salary: "0"],
    "Kristopher Roof" : [.department: "Special Education", .email: "KJRoof@cps.edu", .salary: "0"],
    "Mary Russell" : [.department: "Special Education", .email: "MNRussell@cps.edu", .salary: "0"],
    "Christine Sayers" : [.department: "Special Education", .email: "clsayers@cps.edu", .salary: "0"]
]
